@echo off
echo Starting Next.js setup...
call npx --yes create-next-app@latest modern-landing-page --typescript --tailwind --eslint --app --src-dir --import-alias "@/*" --use-npm
echo Moving files...
xcopy modern-landing-page\* . /E /H /C /I /Y
rd /S /Q modern-landing-page
echo Initializing shadcn...
call npx --yes shadcn@latest init -d
echo Adding shadcn components...
call npx --yes shadcn@latest add button card accordion
echo Installing lucide-react...
call npm install lucide-react
echo Done!
